domain_path: C:\Users\yrosh\Documents\real-fifo\xsa-2107\platform\export\platform\sw\standalone_psu_cortexa53_0
app_src_dir: C:\Xilinx\2025.1\Vitis\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
